README.md

While the library is not yet published to the public npm registry, this should be the preferred method to install it.

chore: add temporary install method

---

.github/trusted-contribution.yml

Release-please app is a trusted contributor and thus does not need to have the `tests: run` label added as the builds will already trigger on the PR.

chore: update trusted-contribution to not include release-please

---

.github/release-trigger.yml

Enables the release-trigger bot to trigger the Kokoro job when the release-please PR is tagged.

build: enable release-trigger bot

---

.gitignore
.kokoro/common.cfg
.kokoro/release/publish.cfg

Switches kokoro build system to use node16 since node14 is still using npm6 which fails to properly build the project since it did not respect the lifecycle scripts when publishing.

fix: publishing build system

---

.github/workflows/tests.yml
package.json

This changeset fixes a problem in the build system that was failing to properly update module imports to include the `.js` file extension.
Fixes: https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/issues/53

fix: esm dist target

---

.github/workflows/lint.yml

No need to run lint on push events

ci: remove lint on push trigger

---

.github/workflows/labels.yml
.github/workflows/lint.yml
.github/workflows/tests.yml

Take care of most `Pinned-Dependencies` and `Token-Permissions` alerts

chore: pin action shas and make workflow read-all

---

src/cloud-sql-instance.ts
src/connector.ts
src/index.ts
src/ip-addresses.ts
src/sqladmin-fetcher.ts
test/cloud-sql-instance.ts
test/connector.ts
test/index.ts
test/ip-addresses.ts

Changing `IpAdressesTypes` to `IpAddressTypes`, removing double pluralization and typo

refactor!: update `IpAdressesTypes` to `IpAddressTypes`

---

src/connector.ts
test/connector.ts

Changed the error code for mismatching ip types in order to avoid it sharing the same error code as a the previously defined invalid instance info error.

refactor: change ip type error code

---

package.json
test/connector.ts

Add unit tests for mismatching ip types in `test/connector.ts`

chore: add tests for mismatch ip types

---

README.md
src/connector.ts
test/connector.ts

Providing a `authType` property should be optional and default to `PASSWORD` instead of throwing an error.

refactor: auth type should default to password

---

test/index.ts

Adding a small check for `AuthTypes` export on index file in order to get to 100% unit test coverage.

chore: add check for auth types export

---

.kokoro/publish.sh
.kokoro/release/publish.cfg

The release job will now build the package .tgz and report it to Kokoro using `define_artifacts` so that
Kokoro can generate an SBOM for this artifact.

chore(ci): Track released artifacts for EO 14028 compliance.

---

scripts/fixup.cjs
src/sqladmin-fetcher.ts

This changeset fixes the number reported by the library in it's SQL Admin request user-agent header.
Fixes: https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/issues/92

fix: user-agent version number

---

src/cloud-sql-instance.ts
src/connector.ts
src/socket.ts
test/cloud-sql-instance.ts
test/socket.ts

Moves the definition of the `port` value to `CloudSQLInstance`, allowing it to be exposed to drivers that might need that value (such as `tedious`) while also making it so that the `port` value is defined in the same place as `host`.
Relates to: https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/issues/66

refactor: move port value to cloud sql instance

---

src/connector.ts
test/connector.ts

This changeset removes the property `ssl: false` that was set to the returned object of the `Connector.getOptions()` method.
This should fix type problems when using the connector alongside the `mysql2` in TypeScript, since that defined value is incompatible with the type definitions for that driver.
Fixes: https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/issues/116

refactor!: remove returned ssl property

---

system-test/mysql2-connect.ts

This changeset adds TypeScript end-to-end tests to ensure that the final
user experience works as intended for TS users using mysql2.
Fixes: https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/issues/119
Depends on: https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/pull/120

chore: add mysql2 end to end test in typescript

---

src/connector.ts
system-test/mysql2-connect.ts

The `authType` param from `Connector.getOptions()` method should be optional also when using TypeScript. In its current shape the defined interface for `ConnectionOptions` don't allow for that, this changeset fixes that problem and updates the TypeScript end-to-end test.

fix: auth type should be optional in typescript

---

package-lock.json
package.json
system-test/pg-connect.ts

This changeset adds TypeScript end-to-end tests to ensure that the final user experience works as intended for TS users.
Fixes: https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/issues/118
Depends on: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65527

chore: add pg end-to-end tests in typescript

---

README.md
src/connector.ts
system-test/mysql2-connect.cjs
system-test/mysql2-connect.mjs
system-test/mysql2-connect.ts
system-test/pg-connect.cjs
system-test/pg-connect.mjs
system-test/pg-connect.ts
test/connector.ts

Making `ipType` optional within `getOptions` and default to `'PUBLIC'`
Closes #126

fix: make `ipType` optional and default to public

---

.github/workflows/coverage.yml

This changeset introduces a CI check that validates that a new PR never has less coverage than the current code coverage value of the main branch.
Fixes: https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/issues/45

chore: add coverage check ci

---

.github/workflows/tests.yml

Bug with windows node 14 builds are causing CI to fail. Turning off this matrix combination for now.

ci: disable windows node 14 builds

---

README.md

Adding note that Connector is alternative to Cloud SQL Auth Proxy.
Closes #141

chore: add note about connector vs proxy

---

package.json

These keywords can be used by search engines when looking up the npm registry and will also render nicely in
https://www.npmjs.com/package/@google-cloud/cloud-sql-connector

chore: add package.json keywords

---

README.md
src/ip-addresses.ts
src/sqladmin-fetcher.ts
test/ip-addresses.ts

This PR adds support to a new `IpAddressTypes.PSC` ip type to support conections to Cloud SQL private service connect.
Ref: https://cloud.google.com/vpc/docs/private-service-connect

feat: add support to PSC ip type

---

package-lock.json
package.json
src/sqladmin-fetcher.ts
test/sqladmin-fetcher.ts

Adds a custom `gaxios` config to be used in `google-auth-library` requests, setting a proper retry value. This should fix the flaky tests on CI and provide a more resilient solution to end users.
Fixes: https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/issues/134
Fixes: https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/issues/146

fix: retry failed google-auth-library requests

---

.github/workflows/tests.yml
.npmrc
package-lock.json
package.json

Enabling lockfile info for `npm6` (`lockfile-version=2`) combined with using `npm ci` for CI installs will make sure that the current `node14` setup that uses the legacy `npm6` version only tries to install the expected version of direct and transitive dependencies.
Note: The custom `lockfile-version=2` value in `.npmrc` file can be removed once `node14` is no longer supported.

chore: enable node14 / npm6 lockfile info on ci

---

tsconfig-base.json
tsconfig-esm.json
tsconfig.json

Adjusting the tsconfig values to allow for usage of an esm-only dependency.
For reference, this is the only meaningful difference in `dist` output, due to **tsc** no longer transpiling dynamic import expressions in CommonJS output (supported since node13):
```patch
diff --git a/dist/cjs/node-crypto.js b/dist/cjs/node-crypto.js
index v0.5.1..v0.5.2-dev 100644
--- a/dist/cjs/node-crypto.js
+++ b/dist/cjs/node-crypto.js
@@ -12,29 +12,6 @@
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
-var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
-    if (k2 === undefined) k2 = k;
-    var desc = …
```

chore: refactor tsconfig to support esm deps

---

scripts/fixup.cjs

Updates `fixup` script to append `.js` extension for imports in `dist/mjs/**/*.d.ts` files, too.
From [Typescript docs](https://www.typescriptlang.org/docs/handbook/esm-node.html#type-in-packagejson-and-new-extensions):
> relative import paths need full extensions (e.g we have to write import "./foo.js" instead of import "./foo")
[bug/issue](https://github.com/GoogleCloudPlatform//issues/new/choose)
before writing your code! That way we can discuss the change, evaluate
designs, and agree on the general idea.
- Fixes: #214

fix: add .js ext. for mjs imports in .d.ts files

---

src/cloud-sql-instance.ts
src/connector.ts
src/time.ts
test/cloud-sql-instance.ts
test/time.ts

When an instance already have active connections, it should not throw errors when trying to refresh cloud instance certificates in the background. Otherwise these errors will bubble up and stop the end user application.
This PR fixes it by adding a more resilient system to the CloudSQLInstance refresh logic that silents errors occured during refresh and keeps valid certificate data that can be used if a refresh is still ongoing or if any error happens when during a refresh.
Fixes: https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/issues/201

fix: silent refresh errors on active connection

---

.github/workflows/tests.yml

Removing deprecated node19 version from CI since it's currently having problems to run on GitHub actions.
Refs: https://github.com/actions/setup-node/issues/838

chore: remove node19 from CI

---

src/connector.ts
src/sqladmin-fetcher.ts
test/connector.ts
test/serial/connector-integration.ts
test/sqladmin-fetcher.ts

Allows library users to optionally pass custom
SQL Admin API endpoint in the Connector constructor.
Fixes: #64

feat: support custom SQL Admin API endpoint

---

README.md
src/connector.ts
src/sqladmin-fetcher.ts
test/sqladmin-fetcher.ts

Adds custom auth support for `auth` and `loginAuth`.
[bug/issue](https://github.com/GoogleCloudPlatform//issues/new/choose)
before writing your code! That way we can discuss the change, evaluate
designs, and agree on the general idea.
- Fixes #200

feat(SQLAdminFetcher): Support base `AuthClient` for `auth` and `loginAuth`

---

src/cloud-sql-instance.ts
test/cloud-sql-instance.ts

Mixing async/await syntax with thenable method chaining was leading to a promise chain that can potentially error with no handler, resulting in a possible unhandled rejection.
This PR fixes it by making sure a single promise chain is returned in place.

fix: cloud-sql-instance promise chaining

---

test/fixtures/setup-tls-server.ts
test/socket.ts

While updating to the new version of our test framework, the tests would start occasionally fail with an `EADDRINUSE` error from trying to connect to an already in use port.
This changeset adds an option to the `setup-tls-server` helper module so that we can use different ports in different files that may be run in parallel.

chore: add port option to tls server test helper

---

.github/workflows/coverage.yml
.github/workflows/tests.yml
package-lock.json
package.json
scripts/tap16-adapter.js
test/cloud-sql-instance.ts
test/connector.ts
test/crypto.ts
test/sqladmin-fetcher.ts
test/x-serial/connector-integration.ts

Replaces https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/pull/211 since we need to update multiple GitHub Actions workflows.
Closes https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/pull/211

deps: update dependency tap to v18

---

.github/workflows/tests.yml

The node14 target runs in an older version of our test framework, skipping flakybot is going to help reducing the number of moving parts to manage in this custom CI setup.

chore: skip flakybot run on node14

---

.github/workflows/tests.yml
package-lock.json
package.json

Both `ts-node` and `c8` are no long required as direct dev dependencies as they're now internal implementation details to `tap@18`.

deps: remove ts-node and c8

---

.github/workflows/tests.yml

npm6 is having trouble installing eslint-related dependencies ([ref](https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/actions/runs/6958954655/job/18935508926?pr=255))
This uninstalls any eslint-related deps since they're not used by the unit or system test ci targets in order to fix builds.

chore: fix node14 ci target install

---

.github/workflows/tests.yml

Node.js v20 is the [current active LTS version](https://github.com/nodejs/Release#release-schedule) and we should have it as part of our test matrix.

chore: add node20 ci target

---

README.md

Moves "APIs and Services" and "Credentials" under "Installation" rather than "Usage" since they're mentioning requirements, also the first paragraph of the "Usage" section mentions: "the following examples" which is weird if we have these sections before the actual examples.

docs: move readme requirements

---

examples/knex/mysql2/connect.cjs
examples/knex/mysql2/connect.mjs
examples/knex/mysql2/connect.ts
examples/knex/mysql2/test/connect.cjs
examples/knex/mysql2/test/connect.mjs
examples/knex/mysql2/test/connect.ts
examples/knex/pg/connect.cjs
examples/knex/pg/connect.mjs
examples/knex/pg/connect.ts
examples/knex/pg/test/connect.cjs
examples/knex/pg/test/connect.mjs
examples/knex/pg/test/connect.ts
examples/knex/tedious/connect.cjs
examples/knex/tedious/connect.mjs
examples/knex/tedious/connect.ts
examples/knex/tedious/test/connect.cjs
examples/knex/tedious/test/connect.mjs
examples/knex/tedious/test/connect.ts

Fixes a naming mistake on `knex` examples.

chore: fix database name on knex examples

---

src/sqladmin-fetcher.ts

This PR missed a commit to support the supplied `GoogleAuth` for `auth`:
- https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/pull/238
[bug/issue](https://github.com/GoogleCloudPlatform//issues/new/choose)
before writing your code! That way we can discuss the change, evaluate
designs, and agree on the general idea.
- #272

fix(SQLAdminFetcher): Use `loginAuth` for `auth`

---

README.md

Adding a details to examples of using the custom `GoogleAuth` creds with a service account other than ADC. 
Ref: https://cloud.google.com/nodejs/docs/reference/google-auth-library/latest#loading-credentials-from-environment-variables
Fixes #272

docs: add details to further examples for `GoogleAuth` credentials

---

README.md

Adds an example on how to use the constructor `auth` property to set a custom auth instance that defines a custom quota project id to be used.
Fixes: https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/issues/62

docs: set custom quota project via custom auth

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/documentation-issue.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/question.md

If a person has made it to GitHub, they almost certainly have an issue with the library and don't need to circle back to support. By removing this phrase, we don't confuse customers and make it clear that we're happy to engage here. If a customer does in fact have a support issue, we can direct them accordingly.

chore: remove support contract reference from template

---

.github/labels.yml

Need `autorelease: triggered` to re-trigger release-trigger builds on release PRs

chore: add `autorelease: triggered` label

---

.github/workflows/tests.yml

Help reduce quota and flaky tests by reducing test builds being run. Test min and max supported version with the edge case that 14.x is not run on Windows so we will also run 16.x builds.
This should reduce flaky tests due to quota issues surrounding too many builds. If flaky tests are still appearing I will pare down further.
Fixes #265 
Fixes #267 
Fixes #271
Fixes #287 
Fixes #307 
Fixes #319
Fixes #322 
Fixes #323

ci: pare down tests builds

---

.github/workflows/tests.yml

It seems Github Actions is now only supporting Node 14 on Linux now, dropping macos as they had windows already.
Will leave ubuntu 14.x build as our sole 14.x build

ci: remove macos 14.x builds

---

src/connector.ts
test/connector.ts

When the metadata of a Cloud SQL instance is fetched via the `connectSettings` API, the connector caches all IP addresses and types. Thus it has the information required to connect via either Public or Private IP. 
The Node Connector currently incorrectly errors when a user switches IP types between consecutive calls... this PR removes the incorrect erroring and allows for the following usage:
```js
import mysql from 'mysql2/promise';
import { Connector } from '@google-cloud/cloud-sql-connector';
const connector = new Connector();
// establish connection via Public IP
var clientOpts = await connector.getOptions({
instanceConnectionName: 'my-project:us-central1:my-instance',
ipType: 'PUBLIC',
});
const conn = await mysql.createConnection({
...clientOpts,
user: 'root',
password: …
```

fix: enable IP type switching

---

.github/renovate.json5

Currently `devDependencies` in package-lock.json are not being bumped by renovate. This PR changes that for them to be bumped once a week on Monday mornings.
Ref: https://github.com/renovatebot/renovate/discussions/15620
Closes #317 
Closes #190

chore: automate updating devDependencies

---

examples/prisma/mysql/connect.cjs
examples/prisma/mysql/connect.mjs
examples/prisma/mysql/connect.ts
examples/prisma/postgresql/connect.cjs
examples/prisma/postgresql/connect.mjs
examples/prisma/postgresql/connect.ts
src/connector.ts

Adding explicit comment to Prisma examples to explain the `close()`
method returned by `connect()`.
The `close()` should be called when done with Prisma to gracefully disconnect
client and cleanup the `Connector` which deletes all local Unix socket files.
Closes #345

chore: add comment about closing PrismaClient and Connector

---

README.md

The `.startLocalProxy` method of the `Connector` is only supported for
MySQL and PostgreSQL Cloud SQL instances and not SQL Server.
This is due to SQL Server not supporting Unix domain sockets.
Adding note to README to make this clear.
Fixes #362

docs: add note that `startLocalProxy` does not support SQL Server

---

src/connector.ts

The `.startLocalProxy` method of starting a local Unix socket
to connect over used `.once` which was an oversight. This only
allows a single connection via the socket. For a connection pool
to leverage several connections at once we should use `.on`.
Tested using Prisma's [`connection_limit`](https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/databases-connections/connection-pool#setting-the-connection-pool-size) query argument.
Using `.once` only works with `connection_limit=1` while using
`.on` allows for `connection_limit=2` etc.
Fixes #349

fix: allow multiple connections via `.startLocalProxy` socket

---

package-lock.json
src/sqladmin-fetcher.ts

This commit fixes the retry behavior of the two SQL Admin API calls.
Any response that results in a 50x error will now be retried up to
5 times with exponential backoff. Using gaxios default exponential backoff.
Previously the Node Connector was only retrying 3 times and for 
all error codes.
Updating gaxios version to have newer params available.
Fixes #371

fix: only retry 5xx Cloud SQL Admin API errors

---

.github/workflows/tests.yml

Pull request from forks once merged will still be skipped because `github.event.pull_request.head.repo.full_name` will still be that of the fork.
To combat this we run the job on all events that are not a pull_request (aka `schedule` and `push`)

ci: skip int and sample tests from forks

---

package-lock.json

Bump dependencies for security fixes via running `npm audit fix`

chore: bump dependencies for security fixes

---

src/connector.ts
src/sqladmin-fetcher.ts
test/connector.ts

Add support for custom user agent via user agent comments.
HTTP user agent's take the form of `<product> / <product-version> <comment>`
Previously, we did not allow support for the `comment` field, leaving no way
to customize a user agent:
https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/blob/5bbd6be6692c8d82e8fb046fec889109e4778e7b/src/sqladmin-fetcher.ts#L110-L114
This PR changes that by adding `userAgent` as a supported `ConnectorOptions`
which will be passed and used to set the `comment` field, allowing customizations
to the user agent.
```js
const connector = new Connector({ userAgent: 'custom-agent'})
```
Closes: #401 
Ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

feat: add support for custom user agent

---

src/cloud-sql-instance.ts
src/connector.ts
test/cloud-sql-instance.ts

Add CloudSqlInstance.close() to stop the refresh cycle permanently. 
Change CloudSqlInstance.forceRefresh() so that it schedules a refresh and returns immediately. 
This should not return a promise. Update test cases to account for changes.

refactor: Improve the refresh to allow connectors to close, part of #421.

---

src/dns-lookup.ts
src/instance-connection-info.ts
src/parse-instance-connection-name.ts
test/cloud-sql-instance.ts
test/dns-lookup.ts
test/parse-instance-connection-name.ts

Update `InstanceConnectionName` and `parseInstanceConnectionName()` to allow DNS names 
as well as instance connection names. Add test cases to cover DNS Names. Add new dns-lookup.ts
that looks up the instance connection name from a DNS name using the TXT record.
Part of #421

chore: Add domainName to instance configuration, part of #421.

---

src/cloud-sql-instance.ts
src/connector.ts
test/cloud-sql-instance.ts
test/connector.ts

The connector may be configured to use a DNS name to look up the instance
name instead of configuring the connector with the instance name directly.
Add a DNS TXT record for the Cloud SQL instance to a private DNS server
or a private Google Cloud DNS Zone used by your application. For example:
Record type: TXT
Name: prod-db.mycompany.example.com – This is the domain name used by the application
Value: my-project:region:my-instance – This is the instance connection name
Configure the dialer with the cloudsqlconn.WithDNSResolver() option.
Open a database connection using the DNS name:
```
const clientOpts = await connector.getOptions({
domainName: "db.example.com",
});
```
Part of #421
See also: https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/843

feat: Configure the connector using a DNS name.

---

package-lock.json
package.json
src/connector.ts
src/socket.ts
src/sqladmin-fetcher.ts
test/socket.ts
test/sqladmin-fetcher.ts

When the the Cloud SQL Instance reports that it has a DNS Name, the connector will use standard TLS hostname validation when checking the server certificate. Now, the server's TLS certificate must contain a SAN record with the instance's DNS name.
The ConnectSettings API added a field dns_names which contains all of the valid DNS names for
an instance.
See also: https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/954

feat: Use standard TLS hostname validation for instances with DNS names

---

.ci/cloudbuild.yaml

This PR enables private IP tests for Cloud SQL instances with the help of Cloud Build private pool
Introduced a new environment variable - IP_TYPE which is set as "PRIVATE" for PSA tests in the cloudbuild.yaml file
Before reviewing this PR, please review: https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/pull/433

ci: add cloudbuild config for PSA tests 

---

src/socket.ts
test/socket.ts

This updates the logic used by the connector to validate server certificates.
When connecting to the instance, the connector's TLS validator will first check the SAN field,
and then if that fails check the CN field in the certificate for the instance name. This will enable
the connector to work smoothly with both legacy and newer instances.
To summarize the deviations from standard TLS hostname verification:
Historically, Cloud SQL creates server certificates with the instance name in the Subject.CN field in 
the format "my-project:my-instance". The connector is expected to check that the instance name
that the connector was configured to dial matches the server certificate Subject.CN field. Thus, 
the Subject.CN field for most Cloud SQL instances does not contain a well-formed DNS Name. …

feat: Update TLS validation to use both SAN and CN fields.

---

.gitignore
build.sh
package.json

Adds the a standardized developer commands script build.sh that will exist in this and all other 
Cloud SQL Connector projects.
GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#2122

chore: Add standard build.sh developer script. 
